# -*- coding: utf-8 -*-
"""Test Split of Part/Session IDs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J-fVue8vhOXAovQFQWz36BbBuMu6GGfb
"""

ts = "b9191659-c598-403a-888d-2fc94e6bd1fb_21817"
ts2 = "b9191659-c598-403a-888d-2fc94e6bd1fb"

ts.split("_")
ts2.split("_")

def get_session_participant(session_id):
  id_split = session_id.split("_")

  if len(id_split) == 1:
    session_id = session_id
    participant_id = ""
  elif len(id_split) == 2:
    session_id = id_split[0]
    participant_id = id_split[1]

  return participant_id, session_id

get_session_participant(ts)

get_session_participant(ts2)